# Be sure to restart your server when you modify this file.
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c62448ac41ce2e46f335e823fb1942f7de9ff26076d42598eb29fe6a6c30590139dcb54cbad2190b3cf708979e46e5995c910344c5e8e02f7cdb68b7ffd523b

test:
  secret_key_base: 5208b44f92b266ddae5582a1cbaeb438ddedc219d2568a8da23b78fbef734fbad89068857f8fb600aabb3f609dbea869a6e02c45978b311cc7f0cfcc3411ba34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
